apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: {{ .Values.namespace }}
  labels:
    app: client
spec:
  containers:
    - name: client
      image: jordi/ab
      command: ['sh', '-c', 'while true; do wget -qO- http://webserver.{{ .Values.namespace }}.svc.cluster.local; sleep 10; done']
    - name: datadog-agent
      image: gcr.io/datadoghq/agent:latest
      env:
        - name: DD_API_KEY
          value: "{{ .Values.datadog.apiKey }}"
        - name: DD_SITE
          value: "{{ .Values.datadog.site }}"
      resources:
        limits:
          memory: "256Mi"
          cpu: "200m"
