apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: {{ .Values.namespace }}
  labels:
    app: webserver
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
